services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: israel
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: domotica          # ← la BD que sí existe
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # comprueba que el servidor acepte conexiones a la BD domotica
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 10

  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy    # ✅ espera hasta que el healthcheck sea OK

volumes:
  postgres_data:
